### ISSUE TITLE
Sidekiq stuck in redis-client buffered_io

### ISSUE THREAD

**Issue by mperham** [redis-rb/redis-client#96]
Like #92, I'm seeing enough people raise a similar issues that I think there's a subtle bug somewhere. The bug results in a Sidekiq process hanging, with all threads blocked on the same backtrace as #92.

I don't have any more information at this time but I will add more info as I get it.

**Comment by byroot** [comment]
Ack.

**Comment by rishimathur81** [comment]
Have been experiencing this issue on Sidekiq as well:

redis-client (0.12.0) lib/redis_client/ruby_connection/buffered_io.rb in block in fill_buffer at line 145

**Comment by byroot** [comment]
Like 145 is a `raise`, https://github.com/redis-rb/redis-client/blob/ac1f3bffd9c1cef1e2d46a0dee6dc12b333da229/lib/redis_client/ruby_connection/buffered_io.rb#L145. Are you sure that you are talking about the same issue than Mike?

**Comment by rishimathur81** [comment]
```EOFError:EOFError

 fromredis-client (0.12.0) lib/redis_client/ruby_connection/buffered_io.rb:145:in `block in fill_buffer'
 fromredis-client (0.12.0) lib/redis_client/ruby_connection/buffered_io.rb:122:in `loop'
 fromredis-client (0.12.0) lib/redis_client/ruby_connection/buffered_io.rb:122:in `fill_buffer'
 fromredis-client (0.12.0) lib/redis_client/ruby_connection/buffered_io.rb:114:in `ensure_remaining'
 fromredis-client (0.12.0) lib/redis_client/ruby_connection/buffered_io.rb:85:in `getbyte'
 fromredis-client (0.12.0) lib/redis_client/ruby_connection/resp3.rb:113:in `parse'
 fromredis-client (0.12.0) lib/redis_client/ruby_connection/resp3.rb:50:in `load'
 fromredis-client (0.12.0) lib/redis_client/ruby_connection.rb:123:in `read'
 fromredis-client (0.12.0) lib/redis_client.rb:441:in `next_event'
 fromsidekiq (7.0.6) lib/sidekiq/redis_client_adapter.rb:55:in `block in subscribe'
 fromsidekiq (7.0.6) lib/sidekiq/redis_client_adapter.rb:54:in `loop'
 fromsidekiq (7.0.6) lib/sidekiq/redis_client_adapter.rb:54:in `subscribe'
 fromsidekiq-pro (7.0.7) lib/sidekiq/pro/config.rb:65:in `block in listen'
 fromsidekiq (7.0.6) lib/sidekiq/config.rb:156:in `block in redis'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:65:in `block (2 levels) in with'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:64:in `handle_interrupt'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:64:in `block in with'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:61:in `handle_interrupt'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:61:in `with'
 fromsidekiq (7.0.6) lib/sidekiq/config.rb:153:in `redis'
 fromsidekiq (7.0.6) lib/sidekiq/component.rb:28:in `redis'
 fromsidekiq-pro (7.0.7) lib/sidekiq/pro/config.rb:64:in `listen'
 fromsidekiq (7.0.6) lib/sidekiq/component.rb:10:in `watchdog'
 fromsidekiq (7.0.6) lib/sidekiq/component.rb:19:in `block in safe_thread'
RedisClient::ConnectionError:EOFError

 fromredis-client (0.12.0) lib/redis_client/ruby_connection.rb:130:in `rescue in read'
 fromredis-client (0.12.0) lib/redis_client/ruby_connection.rb:121:in `read'
 fromredis-client (0.12.0) lib/redis_client.rb:441:in `next_event'
 fromsidekiq (7.0.6) lib/sidekiq/redis_client_adapter.rb:55:in `block in subscribe'
 fromsidekiq (7.0.6) lib/sidekiq/redis_client_adapter.rb:54:in `loop'
 fromsidekiq (7.0.6) lib/sidekiq/redis_client_adapter.rb:54:in `subscribe'
 fromsidekiq-pro (7.0.7) lib/sidekiq/pro/config.rb:65:in `block in listen'
 fromsidekiq (7.0.6) lib/sidekiq/config.rb:156:in `block in redis'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:65:in `block (2 levels) in with'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:64:in `handle_interrupt'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:64:in `block in with'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:61:in `handle_interrupt'
 fromconnection_pool (2.3.0) lib/connection_pool.rb:61:in `with'
 fromsidekiq (7.0.6) lib/sidekiq/config.rb:153:in `redis'
 fromsidekiq (7.0.6) lib/sidekiq/component.rb:28:in `redis'
 fromsidekiq-pro (7.0.7) lib/sidekiq/pro/config.rb:64:in `listen'
 fromsidekiq (7.0.6) lib/sidekiq/component.rb:10:in `watchdog'
 fromsidekiq (7.0.6) lib/sidekiq/component.rb:19:in `block in safe_thread'

**Comment by vin01** [comment]
Stacktrace from one of the stuck sidekiq processes:

```
WARN: /app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:139:in `wait_readable'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:139:in `block in fill_buffer'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:122:in `loop'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:122:in `fill_buffer'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:114:in `ensure_remaining'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:85:in `getbyte'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection/resp3.rb:113:in `parse'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection/resp3.rb:50:in `load'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection.rb:125:in `block in read'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection/buffered_io.rb:48:in `with_timeout'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/ruby_connection.rb:125:in `read'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/connection_mixin.rb:18:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client.rb:271:in `block (2 levels) in blocking_call'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/middlewares.rb:16:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client.rb:270:in `block in blocking_call'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client.rb:626:in `ensure_connected'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client.rb:269:in `blocking_call'
/app/vendor/bundle/ruby/2.7.0/gems/redis-client-0.12.1/lib/redis_client/decorator.rb:26:in `blocking_call'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/fetch.rb:47:in `block in retrieve_work'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/capsule.rb:101:in `block in redis'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/app/vendor/bundle/ruby/2.7.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/capsule.rb:98:in `redis'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:26:in `redis'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/fetch.rb:47:in `retrieve_work'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:87:in `get_one'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:99:in `fetch'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:81:in `process_one'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/processor.rb:72:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:8:in `watchdog'
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-7.0.3/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

**Comment by mperham** [comment]
Please try to reproduce the issue with the **latest** Sidekiq and redis-client gem versions.

**Comment by casperisfine** [comment]
Even then, that's interesting.

So according to the backtrace, it's blocked on:

```ruby
TIMEOUT = 2
queue, job = redis { |conn| conn.blocking_call(false, "brpop", *qs, TIMEOUT) }
```

It's getting late here, but I'll see if I can either repo or at least theorize on what could happen.

**Comment by casperisfine** [comment]
I found a mitigation at least: https://github.com/sidekiq/sidekiq/pull/5823

**Comment by rishimathur81** [comment]
Added [d36c090](https://github.com/sidekiq/sidekiq/commit/d36c0907a8720f8c7728d9102f5a75f87145cae7) as a patch and deployed. 

Still getting the EOF error after deploying.

**Comment by byroot** [comment]
I'm confused, is the worker stuck or throwing EOF errors? That sounds contradictory to me...

Also what I'd like to see in reports:

  - What is your redis server version and provider.
  - Are you connecting using SSL (that changes a lot of things).
  - Have you tried `hiredis-client` (not suggesting as long term thing, but interesting to see if it handles better whatever network issue you are having)

**Comment by rishimathur81** [comment]
- We are using Managed DB Redis 7 from Digital Ocean
- Yes SSL is being used to connect
- Have not tried hiredis-client. We can test this out and see if it resolves.
- This issue only started happening after we upgraded from sidekiq-pro 5.x.x. to sidekiq-pro 7.x.x. We were still using the same managed instance of Redis 7 with sidekiq-pro 5.x.x

**Comment by mperham** [comment]
FYI, `EOFError` is what you will see if Redis shuts down. You will see this error occasionally when doing server migrations or maintenance downtime. It's not always a sign of something wrong.

```
% irb
irb(main):001:0> require 'redis-client'
irb(main):002:0> r = RedisClient.new
irb(main):004:0> r.call("set", "foo", "bar")
=> "OK"
irb(main):005:0> r.call("get", "foo")
=> "bar"

[...shut down Redis...]

irb(main):006:0> r.call("get", "foo")
/Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.14.0/lib/redis_client/ruby_connection.rb:101:in `rescue in read': EOFError (RedisClient::ConnectionError)                                                              
        from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.14.0/lib/redis_client/ruby_connection.rb:92:in `read'
        from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.14.0/lib/redis_client/connection_mixin.rb:31:in `call'
        from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.14.0/lib/redis_client.rb:211:in `block (2 levels) in call'
        from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.14.0/lib/redis_client/middlewares.rb:16:in `call'
        from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.14.0/lib/redis_client.rb:210:in `block in call'
        from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.14.0/lib/redis_client.rb:626:in `ensure_connected'
        from /Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.14.0/lib/redis_client.rb:209:in `call'
        from (irb):6:in `<main>'                   
        from /Users/mperham/.rubies/ruby-3.2.0/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
	from /Users/mperham/.gem/ruby/3.2.0/bin/irb:25:in `load'
	from /Users/mperham/.gem/ruby/3.2.0/bin/irb:25:in `<main>'
/Users/mperham/.gem/ruby/3.2.0/gems/redis-client-0.14.0/lib/redis_client/ruby_connection/buffered_io.rb:145:in `block in fill_buffer': EOFError (EOFError)
```

**Comment by bogn83** [comment]
> I found a mitigation at least: [sidekiq/sidekiq#5823](https://github.com/sidekiq/sidekiq/pull/5823)

So far I can only say that above PR/unreleased commit https://github.com/sidekiq/sidekiq/commit/d36c0907a8720f8c7728d9102f5a75f87145cae7 processed our heavy load of jobs fine from Friday on. The stuck worker with the [trace from vin01 above](https://github.com/redis-rb/redis-client/issues/96#issuecomment-1462724641) hasn't happened yet, but that's not meaning too much as it only happened for us when the datacenter had network delay. Delay seems to have not occurred so far.

**Comment by byroot** [comment]
I'm gonna assume this is fixed. If not let me know.

**Comment by vin01** [comment]
I am still seeing this in `0.14.1`, from the thread dump:

```
2023-07-16 pid=1 tid=16yp WARN: /app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connectio
n/buffered_io.rb:139:in `wait_readable'
/app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:139:in `block in fill_buffer'
/app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:122:in `loop'
/app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:122:in `fill_buffer'
/app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:114:in `ensure_remaining'
/app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/buffered_io.rb:85:in `getbyte'
/app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/resp3.rb:113:in `parse'
/app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection/resp3.rb:50:in `load'
/app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client/ruby_connection.rb:94:in `read'
/app/vendor/bundle/ruby/3.2.0/gems/redis-client-0.14.1/lib/redis_client.rb:441:in `next_event'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-pro-7.1.3/lib/sidekiq/pro/config.rb:65:in `block in event_loop'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-pro-7.1.3/lib/sidekiq/pro/config.rb:64:in `loop'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-pro-7.1.3/lib/sidekiq/pro/config.rb:64:in `event_loop'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-pro-7.1.3/lib/sidekiq/pro/config.rb:83:in `block in listen'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.2/lib/sidekiq/config.rb:164:in `block in redis'
/app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
/app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
/app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
/app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
/app/vendor/bundle/ruby/3.2.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.2/lib/sidekiq/config.rb:161:in `redis'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.2/lib/sidekiq/component.rb:28:in `redis'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-pro-7.1.3/lib/sidekiq/pro/config.rb:78:in `listen'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.2/lib/sidekiq/component.rb:10:in `watchdog'
/app/vendor/bundle/ruby/3.2.0/gems/sidekiq-7.1.2/lib/sidekiq/component.rb:19:in `block in safe_thread'
```

It remains stuck and no Sidekiq jobs are processed until restarted. After restart, processing resumes.

**Comment by casperisfine** [comment]
@vin01 the backtrace you show is from a Sidekiq-pro feature that spawns a background thread and is listening on Redis pub/sub, so it's normal for it to block forever.

If there was a problem in your process it likely wasn't in this thread.

**Comment by bogn83** [comment]
After https://github.com/redis-rb/redis-client/issues/96#issuecomment-1467590276 we are still haunted by stuck queues. With the mentioned commit it got better, meaning it's less chaotic which workers get stuck and when. Now it's always the one on the heavy error-rate queue (lots of failing HTTP requests) and always vaguely 40 hours after the last deploy but the timing is too erratic to point to something scheduled being the root cause IMHO.

Should you want thread dumps here they are  [thread_dumps.zip](https://github.com/redis-rb/redis-client/files/12255890/thread_dumps.zip)

@mperham 
What we can surely tell though is that this custom sidekiq patch of ours is no longer sending logs once that worker gets stuck (it looks normal from the outside, it's just not doing anything anymore). Logs stop directly where jobs stop being processed:
![image](https://github.com/redis-rb/redis-client/assets/42942941/1925e428-7205-4dd5-9915-cd2faea7c710)
